export const PINYIN_DATA = {
    initials: [
        { char: 'b', mnemonic: '听听广播 b b b', illustration: '📻' },
        { char: 'p', mnemonic: '泼水洗脸 p p p', illustration: '💦' },
        { char: 'm', mnemonic: '两个门洞 m m m', illustration: '🚪' },
        { char: 'f', mnemonic: '一根拐棍 f f f', illustration: '🦯' },
        { char: 'd', mnemonic: '小马跑步 d d d', illustration: '🐎' },
        { char: 't', mnemonic: '伞把儿弯弯 t t t', illustration: '⛱️' },
        { char: 'n', mnemonic: '一个门洞 n n n', illustration: '🛖' },
        { char: 'l', mnemonic: '一根棍子 l l l', illustration: '🥖' },
        { char: 'g', mnemonic: '鸽子唱歌 g g g', illustration: '🕊️' },
        { char: 'k', mnemonic: '蝌蚪游泳 k k k', illustration: '🐸' },
        { char: 'h', mnemonic: '杯子喝水 h h h', illustration: '🥤' },
        { char: 'j', mnemonic: '萌萌小鸡 j j j', illustration: '🐥' },
        { char: 'q', mnemonic: '气球飞舞 q q q', illustration: '🎈' },
        { char: 'x', mnemonic: '西瓜切开 x x x', illustration: '🍉' },
        { char: 'zh', mnemonic: '蜘蛛织网 zh zh zh', illustration: '🕸️' },
        { char: 'ch', mnemonic: '尺子量长 ch ch ch', illustration: '📏' },
        { char: 'sh', mnemonic: '动物之王 sh sh sh', illustration: '🦁' },
        { char: 'r', mnemonic: '红日当头 r r r', illustration: '☀️' },
        { char: 'z', mnemonic: '睡觉打呼 z z z', illustration: '😴' },
        { char: 'c', mnemonic: '刺猬爬坡 c c c', illustration: '🦔' },
        { char: 's', mnemonic: '蚕儿吐丝 s s s', illustration: '🐛' },
        { char: 'y', mnemonic: '小小树杈 y y y', illustration: '🪾' },
        { char: 'w', mnemonic: '小小乌鸦 w w w', illustration: '🐦‍⬛' }
    ],
    simpleFinals: [
        { char: 'a', mnemonic: '圆圆脸蛋扎小辫，张大嘴巴 a a a', illustration: '👧' },
        { char: 'o', mnemonic: '太阳出来红通通，公鸡唱歌 o o o', illustration: '🐓' },
        { char: 'e', mnemonic: '清清池塘一只鹅，水中倒影 e e e', illustration: '🦢' },
        { char: 'i', mnemonic: '穿件衣服戴顶帽，牙齿对齐 i i i', illustration: '👕' },
        { char: 'u', mnemonic: '嘴巴突出像火车，呜呜呜呜 u u u', illustration: '🚂' },
        { char: 'ü', mnemonic: '小鱼吐泡真可爱，吹起口哨 ü ü ü', illustration: '🐟' }
    ],
    compoundFinals: [
        { char: 'ai', mnemonic: '挨着坐好 ai ai ai', illustration: '👫' },
        { char: 'ei', mnemonic: '用力拔萝卜 ei ei ei', illustration: '🥕' },
        { char: 'ui', mnemonic: '围巾暖和 ui ui ui', illustration: '🧣' },
        { char: 'ao', mnemonic: '奥林匹克 ao ao ao', illustration: '🏅' },
        { char: 'ou', mnemonic: '海鸥飞翔 ou ou ou', illustration: '🕊️' },
        { char: 'iu', mnemonic: '邮票寄信 iu iu iu', illustration: '✉️' },
        { char: 'ie', mnemonic: '椰子树上 ie ie ie', illustration: '🌴' },
        { char: 'üe', mnemonic: '圆圆月亮 üe üe üe', illustration: '🌙' },
        { char: 'er', mnemonic: '大大耳朵 er er er', illustration: '👂' },
        { char: 'an', mnemonic: '天安门前 an an an', illustration: '🏛️' },
        { char: 'en', mnemonic: '摁个门铃 en en en', illustration: '🔔' },
        { char: 'in', mnemonic: '树荫乘凉 in in in', illustration: '🌳' },
        { char: 'un', mnemonic: '白云飘飘 un un un', illustration: '☁️' },
        { char: 'ün', mnemonic: '小鱼转圈 ün ün ün', illustration: '🌀' },
        { char: 'ang', mnemonic: '昂起头来 ang ang ang', illustration: '🦒' },
        { char: 'eng', mnemonic: '打开电灯 eng eng eng', illustration: '💡' },
        { char: 'ing', mnemonic: '老鹰飞翔 ing ing ing', illustration: '🦅' },
        { char: 'ong', mnemonic: '一个闹钟 ong ong ong', illustration: '⏰' }
    ],
    wholeSyllables: ['zhi', 'chi', 'shi', 'ri', 'zi', 'ci', 'si', 'yi', 'wu', 'yu', 'ye', 'yue', 'yuan', 'yin', 'yun', 'ying']
};

export const SOUND_MAP = {
    // 声母
    'b': '波', 'p': '坡', 'm': '摸', 'f': '佛',
    'd': '得', 't': '特', 'n': '讷', 'l': '勒',
    'g': '哥', 'k': '科', 'h': '喝',
    'j': '鸡', 'q': '七', 'x': '西',
    'zh': '知', 'ch': '吃', 'sh': '狮', 'r': '日',
    'z': '滋', 'c': '刺', 's': '丝',
    'y': '衣', 'w': '乌',
    // 韵母 (单韵母)
    'a': '阿', 'o': '喔', 'e': '厄', 'i': '衣', 'u': '屋', 'ü': '迂',
    'ā': '阿', 'á': '啊', 'ǎ': '啊', 'à': '啊',
    'ō': '喔', 'ó': '喔', 'ǒ': '喔', 'ò': '喔',
    'ē': '婀', 'é': '额', 'ě': '恶', 'è': '饿',
    'ī': '衣', 'í': '移', 'ǐ': '椅', 'ì': '意',
    'ū': '屋', 'ú': '无', 'ǔ': '五', 'ù': '物',
    'ǖ': '迂', 'ǘ': '鱼', 'ǚ': '雨', 'ǜ': '玉',
    // 复韵母 & 鼻韵母 (简易映射，通常直接读)
    'ai': '哎', 'ei': '诶', 'ui': '威', 'ao': '熬', 'ou': '欧', 'iu': '优',
    'ie': '耶', 'üe': '约', 'er': '儿',
    'an': '安', 'en': '恩', 'in': '因', 'un': '温', 'ün': '晕',
    'ang': '昂', 'eng': '鞥', 'ing': '英', 'ong': '翁'
};

export const CHARACTER_MAP = {
    'ba': ['八', '拔', '靶', '爸'],
    'bo': ['波', '博', '跛', '播'],
    'bi': ['比', '鼻', '闭', '币'],
    'bai': ['掰', '白', '摆', '败'],
    'bei': ['杯', '', '北', '倍'],
    'bao': ['包', '薄', '宝', '报'],
    'bie': ['鳖', '别', '瘪', '别'],
    'ma': ['妈', '麻', '马', '骂'],
    'mi': ['咪', '迷', '米', '密'],
    'fu': ['夫', '福', '府', '父'],
    'da': ['搭', '答', '打', '大'],
    'tu': ['秃', '图', '土', '兔'],
    'ni': ['妮', '尼', '你', '逆'],
    'lu': ['噜', '炉', '鲁', '路'],
    'ge': ['歌', '格', '各', '个'],
    'ke': ['科', '壳', '可', '客'],
    'he': ['喝', '河', '何', '和'],
    'ji': ['机', '级', '几', '计'],
    'qi': ['七', '骑', '起', '气'],
    'xi': ['希', '习', '喜', '细'],
    'yi': ['一', '移', '椅', '意'],
    'wu': ['屋', '无', '五', '务'],
    'yu': ['淤', '鱼', '雨', '玉'],
    'ba': ['八', '拔', '靶', '爸'],
    'bu': ['补', '捕', '部', '不'],
    'pa': ['啪', '爬', '怕', '帕'],
    'pi': ['批', '皮', '否', '屁'],
    'pu': ['扑', '仆', '谱', '瀑'],
    'mo': ['摸', '魔', '抹', '末'],
    'mu': ['木', '目', '母', '模'],
    'fa': ['发', '罚', '法', '发'],
    'fo': ['佛'],
    'di': ['低', '敌', '底', '第'],
    'du': ['嘟', '毒', '赌', '度'],
    'ta': ['他', '塔', '踏', '它'],
    'ti': ['提', '题', '体', '剃'],
    'na': ['拿', '哪', '那', '纳'],
    'nu': ['奴', '努', '怒', '路'],
    'la': ['拉', '喇', '腊', '辣'],
    'li': ['梨', '离', '礼', '力'],
    'gu': ['姑', '古', '鼓', '故'],
    'ka': ['咔', '卡', '咯', '看'],
    'ku': ['哭', '库', '枯', '苦'],
    'hu': ['呼', '胡', '虎', '护'],
    'ju': ['居', '橘', '举', '巨'],
    'qu': ['区', '渠', '取', '去'],
    'xu': ['需', '徐', '许', '续'],
    'gua': ['刮', '画', '寡', '挂'],
    'kua': ['夸', '跨', '跨', '跨'],
    'hua': ['花', '华', '划', '话'],
    'guo': ['锅', '国', '果', '过'],
    'huo': ['豁', '活', '火', '和'],
    'jia': ['家', '夹', '甲', '价'],
    'qia': ['掐', '恰', '洽', '恰'],
    'xia': ['虾', '匣', '下', '吓'],
    'jiao': ['交', '脚', '角', '叫'],
    'qiao': ['敲', '乔', '巧', '俏'],
    'xiao': ['消', '校', '小', '笑'],
    'jian': ['间', '捡', '简', '见'],
    'qian': ['千', '前', '浅', '欠'],
    'xian': ['先', '闲', '显', '现'],
    'juan': ['捐', '卷', '卷', '眷']
};

export const TONE_MAP = {
    'a': ['ā', 'á', 'ǎ', 'à'],
    'o': ['ō', 'ó', 'ǒ', 'ò'],
    'e': ['ē', 'é', 'ě', 'è'],
    'i': ['ī', 'í', 'ǐ', 'ì'],
    'u': ['ū', 'ú', 'ǔ', 'ù'],
    'ü': ['ǖ', 'ǘ', 'ǚ', 'ǜ']
};
